### ISSUE TITLE
Multiple titles of imported publications display texquote in the title

### ISSUE THREAD

**Issue by jdelgadoesteban** [winkm89/teachPress#179] opened 2021-09-27 16:03 UTC
For example:

Coronavirus is a textquoteleftsliding doorstextquoteright moment. What we do now could change Earthtextquoterights trajectory, misc, 2020 (as author)

Is there any way of avoiding this?

Many thanks!

**Comment by winkm89** [comment] 2021-11-06 19:20
Thank you for the data! I think the problem is that Bibtex special characters \textquoteright \textendash were just not recognized. This will be fixed with the next update.

**Comment by jdelgadoesteban** [comment] 2021-11-16 15:06
Michael, that would be great!

Kind Regards

Javier

**Closed** 2021-11-29 18:34 UTC
Labels: bug, solved
